---
title: List of Publications
author: 'Ihaddaden Mohamed El Fodil'
date: '2019-08-04'
slug: list-of-publications
categories: []
tags: []
subtitle: ''
summary: 'Click on "List of Publications" above to have a look at my academic publications'
lastmod: '2019-08-04T23:35:30+02:00'
featured: no
projects: []
---

### Published papers

- [Mohamed El Fodil Ihaddaden, (2020) ''Impact of Political Uncertainty on Banking Productivity: Investigating the Jasmin Revolution Effect on the Tunisian Banking System'', Economics Bulletin, Volume 40, Issue 1, pages 437-447.](http://www.accessecon.com/Pubs/EB/2020/Volume40/EB-20-V40-I1-P37.pdf)

- [Mohamed El Fodil Ihaddaden, (2019) ''Investigating Eurosystem Central Banking Efficiency: A Data Envelopment Analysis Approach'', Revue d'Economie & de Gestion, Volume 03, Issue 1, pages 1-12.](https://poseidon01.ssrn.com/delivery.php?ID=045009089115014002123102117092120088033043069002065054095096000092123072031012004123043028032104020043034081114077094077004092022034064058004081069029086004031098124037042054008096073068007116095083121008015126121122007074005124007030019070112079026073&EXT=pdf)

- [IHADDADEN, M., & BOUHABA, M. (2019). ''A Performance Comparison Between State-Owned, Mixed And Private Banks In Algeria'', Les Cahiers Du CREAD, Volume 35, Issue 1, pages 5-20.](http://revue.cread.dz/index.php/les-cahiers-du-cread/article/view/1189)



### Submitted Papers

- Mohamed El Fodil Ihaddaden, Being State-Owned is not a Fatality: Improving Public Bank's Performance Using the Data Envelopment Analysis Radial and Super-Efficiency Models: An Algerian Case Study.

### Working Papers

- Mohamed El Fodil Ihaddaden, Is there a Relationship between Credit Information Exchange and Entrepreneurship? A Cross Country Evidence.

